// SPDX-License-Identifier: MIT
pragma solidity >=0.8.20 <=0.8.24;
import { IERC20 } from '@openzeppelin/contracts/interfaces/IERC20.sol';

interface IOlympexAsyncOrderV3 {
	/*********
	 * INDEX *
	 *********/
	// 1. Type declarations.
	// 2. Constants and state variables.
	// 3. Events.
	// 4. Errors.
	// 5. Modifiers.
	// 6. Functions.
	// 		Order of functions
	// 		6.1 constructor
	// 		6.2 receive function (if exists)
	// 		6.3 fallback function (if exists)
	// 		6.4 external
	// 		6.5 public
	// 		6.6 internal
	// 		6.7 private

	/**
	 * @notice Describes the details of a order including the tokens, amounts, and execution parameters.
	 * @dev This struct is used to encapsulate the essential details for the order in the contract.
	 */
	struct OrderDescription {
		/// @notice The token being sold in the order.
		/// @dev Source token that the maker provides in the trade.
		IERC20 srcToken;
		/// @notice The token being bought in the order.
		/// @dev Destination token that the maker wants to receive in the trade.
		IERC20 dstToken;
		/// @notice The amount of `srcToken` to be sold in the order.
		/// @dev This is the exact amount of `srcToken` the maker wishes to trade.
		uint256 amount;
		/// @notice The address of the user creating the order (maker).
		/// @dev The maker is the user who initiates the order.
		address maker;
		/// @notice The address of the taker who will fulfill the order.
		/// @dev The taker is the user or contract that fills the order. Can be set to address(0) if not predetermined.
		address taker;
		/// @notice The gas to be used for the execution of the order.
		/// @dev Specifies the maximum amount of gas that can be used during the execution of the order.
		uint256 gasLimit;
		/// @notice The value of ETH to be sent along with the order if needed.
		/// @dev If the order requires a transfer of ETH (e.g., for gas or execution), this value specifies the amount.
		uint256 value;
		/// @notice The calldata for the execution of the order on the aggregator.
		/// @dev Encoded data that includes function signatures and arguments for interacting with external contracts during the order execution.
		bytes data;
		/// @notice The conversion rate for the fee, used to calculate the fee in the destination token.
		/// @dev This value is set by the maker and is used to determine the fee structure for the order.
		uint256 feeConvertionRate;
		/// @notice The signature of the order, used to verify the authenticity of the order.
		/// @dev This signature is generated by the maker and must be provided to fulfill the order.
		bytes signature;
	}

	/*************
	 * 3. EVENTS *
	 *************/

	/**
	 * @notice Emitted when a new limit order is created.
	 * @dev Provides details of the limit order, including recipient, amount, and tokens involved.
	 * @param recipient The address of the user who created the limit order.
	 * @param amount The amount of `srcToken` being sold in the limit order.
	 * @param srcToken The token being sold in the limit order.
	 * @param dstToken The token being bought in the limit order.
	 * @param gasUsed The amount of gas used for the limit order execution.
	 * @param fee The fee charged for the limit order execution.
	 * @param feeInSrcToken The fee charged in `srcToken` for the limit order execution.
	 * @param feeConvertionRate The fee conversion rate for the limit order execution.
	 */
	event LimitOrderEmited(
		address indexed maker,
		address indexed recipient,
		uint256 amount,
		address srcToken,
		address dstToken,
		uint256 gasUsed,
		uint256 fee,
		uint256 feeInSrcToken,
		uint256 feeConvertionRate,
		uint256 gasPrice
	);

	/**
	 * @notice Emitted when an error occurs during the execution of a limit order.
	 * @dev Provides details about the failed limit order attempt, including the error message.
	 * @param recipient The address of the user whose limit order failed.
	 * @param amount The amount of `srcToken` that was involved in the failed order.
	 * @param srcToken The token that was being sold in the failed limit order.
	 * @param dstToken The token that was being bought in the failed limit order.
	 * @param dataError A description or message explaining the cause of the error.
	 */
	event LimitOrderError(
		address indexed recipient,
		uint256 amount,
		address srcToken,
		address dstToken,
		string dataError
	);

	/**
	 * @notice Emitted when a new limit order is created.
	 * @dev Provides details of the limit order, including recipient, amount, and tokens involved.
	 * @param recipient The address of the user who created the limit order.
	 * @param amount The amount of `srcToken` being sold in the limit order.
	 * @param srcToken The token being sold in the limit order.
	 * @param dstToken The token being bought in the limit order.
	 * @param gasUsed The amount of gas used for the limit order execution.
	 * @param fee The fee charged for the limit order execution.
	 * @param feeInDstToken The fee charged in `srcToken` for the limit order execution.
	 * @param feeConvertionRate The fee conversion rate for the limit order execution.
	 */
	event DCAOrderEmited(
		address indexed recipient,
		uint256 amount,
		address srcToken,
		address dstToken,
		uint256 gasUsed,
		uint256 fee,
		uint256 feeInDstToken,
		uint256 feeConvertionRate,
		uint256 gasPrice
	);

	/**
	 * @notice Emitted when an error occurs during the execution of a limit order.
	 * @dev Provides details about the failed limit order attempt, including the error message.
	 * @param recipient The address of the user whose limit order failed.
	 * @param amount The amount of `srcToken` that was involved in the failed order.
	 * @param srcToken The token that was being sold in the failed limit order.
	 * @param dstToken The token that was being bought in the failed limit order.
	 * @param dataError A description or message explaining the cause of the error.
	 */
	event DCAOrderError(
		address indexed recipient,
		uint256 amount,
		address srcToken,
		address dstToken,
		string dataError
	);

	/**
	 * @notice Emitted when the gas has been paid
	 * @dev Provides details the pay of gas used for async swaps
	 * @param maker The address of the user who created the async swap.
	 * @param srcToken The token being sold in the async swap.
	 * @param receiver The address receiving the gas payment.
	 * @param fee The amount paid for gas in wei.
	 * @param srcTokenFee The amount paid for gas in srcToken.
	 * @param referenceGasPrice Value for convert fee in srcToken.
	 */
	event LimitOrderGasPaid(
		address indexed maker,
		address srcToken,
		address receiver,
		uint256 fee,
		uint256 srcTokenFee,
		uint256 referenceGasPrice
	);

	/*************
	 * 4. ERRORS *
	 *************/

	/****************
	 * 5. FUNCTIONS *
	 ****************/

	function pause() external;

	function unpause() external;

	/** @notice Executes a limit order swap through the specified aggregator contract.
	 * @dev Facilitates the swap of tokens using the details provided in `limitOrderData`.
	 * @param aggregatorContract The address of the aggregator contract to execute the swap.
	 * @param middlewareAddress The address of middleware that make the swap used for the aggregator
	 * @param limitOrderData The data structure containing the necessary information for the limit order swap.
	 * @return The amount of `dstToken` received as a result of the swap.
	 */
	function limitOrderSwap(
		address aggregatorContract,
		address middlewareAddress,
		OrderDescription calldata limitOrderData
	) external payable returns (uint256);

	/**
	 * @notice Executes a limit order swap through the specified aggregator contract.
	 * @dev Facilitates the swap of tokens using the details provided in `limitOrderData`.
	 * @param aggregatorContract The address of the aggregator contract to execute the swap.
	 * @param middlewareAddress The address of middleware that make the swap used for the aggregator
	 * @param orderData The data structure containing the necessary information for the limit order swap.
	 * @return The amount of `dstToken` received as a result of the swap.
	 */
	function DCASwap(
		address aggregatorContract,
		address middlewareAddress,
		OrderDescription calldata orderData
	) external payable returns (uint256);

	/**
	 * @notice Executes multiple limit order swaps in a single transaction through the specified aggregator contract.
	 * @dev This function processes an array of limit orders, allowing bulk swaps in one call.
	 * @param aggregatorContract The address of the aggregator contract to execute the bulk swaps.
	 *	@param limitOrderData An array of limit order descriptions, each containing the data for a separate swap.
	 */
	function limitOrderSwapBulk(
		address aggregatorContract,
		address middlewareAddress,
		OrderDescription[] calldata limitOrderData
	) external payable;

	function getVersion() external pure returns (string memory);
}
